Repository fga-eps-mds/2020.2-Projeto-Kokama-Front-end, pull requests merged in 2021-04, with the labels that each got.

#13 Exchange library to handle storage and make respective refactoring
  projeto-kokama/App.tsx
  projeto-kokama/package.json
  projeto-kokama/src/components/Stories.tsx
  projeto-kokama/src/screens/Translation/index.tsx
  projeto-kokama/src/utils/dictionary.ts
  projeto-kokama/src/utils/translation.ts
  projeto-kokama/yarn-error.log
  projeto-kokama/yarn.lock
Labels: 0-MDS, 1-Frontend, bug

#15 Configura os testes do front-end da aplicação
  .github/workflows/tests.yml
  projeto-kokama/.gitignore
  projeto-kokama/package.json
  projeto-kokama/src/utils/translation.test.ts
  projeto-kokama/yarn.lock
Labels: 0-DevOps, 0-EPS, 1-Frontend

#14 Create Spinner and Improve Code
  .gitignore
  projeto-kokama/App.tsx
  projeto-kokama/package.json
  projeto-kokama/src/components/SpinnerLoading.tsx
  projeto-kokama/src/components/Stories.tsx
  projeto-kokama/src/components/TopMenu.tsx
  projeto-kokama/src/index.tsx
  projeto-kokama/src/screens/KokamaStories/index.tsx
  projeto-kokama/src/screens/KokamaStories/styles.ts
  projeto-kokama/src/screens/Learning/index.tsx
  projeto-kokama/src/screens/Story/index.tsx
  projeto-kokama/src/screens/Translation/index.tsx
  projeto-kokama/src/screens/Translation/styles.ts
  projeto-kokama/src/utils/dictionary.ts
  projeto-kokama/yarn.lock
Labels: 0-MDS, 1-Frontend, 3-Technical Story
