Repository fga-eps-mds/2020.2-Projeto-Kokama-Front-end, pull requests merged in 2021-03, with the labels that each got.

#6 101 logo
  projeto-kokama/src/assets/img/logo.png
Labels: 0-MDS, 1-Frontend

#7 95 update history
  projeto-kokama/src/screens/Translation/index.tsx
  projeto-kokama/src/screens/Translation/styles.ts
Labels: 0-MDS, 1-Frontend, 3-User story

#8 Primeira Release - v1.0
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/template-de-bug.md
  .github/ISSUE_TEMPLATE/template-gen-rico-de-issues.md
  .github/ISSUE_TEMPLATE/template-novas-funcionalidades.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  LICENSE
  README.md
  projeto-kokama/.eslintignore
  projeto-kokama/.eslintrc.js
  projeto-kokama/.expo-shared/assets.json
  projeto-kokama/.gitignore
  projeto-kokama/App.tsx
  projeto-kokama/app.json
  projeto-kokama/assets/adaptive-icon.png
  projeto-kokama/assets/favicon.png
  projeto-kokama/assets/icon.png
  projeto-kokama/assets/splash.png
  projeto-kokama/package-lock.json
  projeto-kokama/package.json
  projeto-kokama/src/api/.placeholder
  projeto-kokama/src/assets/img/logo.png
  projeto-kokama/src/components/.placeholder
  projeto-kokama/src/config/constants.ts
  projeto-kokama/src/context/.placeholder
  projeto-kokama/src/index.tsx
  projeto-kokama/src/screens/Translation/dictionary.json
  projeto-kokama/src/screens/Translation/index.tsx
  projeto-kokama/src/screens/Translation/interface.ts
  projeto-kokama/src/screens/Translation/styles.ts
  projeto-kokama/src/utils/.placeholder
  projeto-kokama/tunnel/.expo/README.md
  projeto-kokama/tunnel/.expo/settings.json
  projeto-kokama/yarn.lock
Labels: 0-Architect, 0-Data Analyst, 0-DevOps, 0-EPS, 0-MDS, 0-Product Owner, 0-Scrum Master, 1-Frontend

#10 94 e 95 update dictionary and save history
  projeto-kokama/babel.config.js
  projeto-kokama/package.json
  projeto-kokama/src/api/.placeholder
  projeto-kokama/src/api/Api.ts
  projeto-kokama/src/assets/Colors.ts
  projeto-kokama/src/components/.placeholder
  projeto-kokama/src/components/History.tsx
  projeto-kokama/src/components/HistoryTitle.tsx
  projeto-kokama/src/components/TopMenu.tsx
  projeto-kokama/src/config/constants.ts
  projeto-kokama/src/config/urls.ts
  projeto-kokama/src/index.tsx
  projeto-kokama/src/screens/Translation/dictionary.json
  projeto-kokama/src/screens/Translation/index.tsx
  projeto-kokama/src/screens/Translation/interface.ts
  projeto-kokama/src/screens/Translation/styles.ts
  projeto-kokama/src/utils/.placeholder
  projeto-kokama/src/utils/dictionary.ts
  projeto-kokama/src/utils/translation.ts
  projeto-kokama/yarn-error.log
  projeto-kokama/yarn.lock
Labels: 0-MDS, 1-Backend, 1-Frontend, 3-User story
